/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CompileResult {
  source: string
  discoveries: Array<Discovery>
}

export declare function compileScript(source: string, fileName: string): CompileResult

export type Discovery =
  | { type: 'Route', frame: RouteFrame, path: string, export: string }

export declare const enum RouteFrame {
  Layout = 'layout',
  Page = 'page'
}
