/* auto-generated by NAPI-RS */
/* eslint-disable */
export type CompilerDiagnosticTier =
  | { type: 'Error' }
  | { type: 'Related', field0: DiagnosticId }

export interface CompileResult {
  source: string
  discoveries: Array<Discovery>
  diagnostics: Array<NapiCompilerDiagnostic>
}

export declare function compileScript(source: string, fileName: string): CompileResult

export interface DiagnosticId {
  field0: number
}

export type Discovery =
  | { type: 'Route', frame: RouteFrame, path: string, export: string }

export interface NapiCompilerDiagnostic {
  message: string
  span: [number, number]
  tier: CompilerDiagnosticTier
  id: DiagnosticId
}

export declare const enum RouteFrame {
  Layout = 'layout',
  Page = 'page'
}
